name = "alcohol-worker"       # Tên dự án Worker hiển thị trên Cloudflare
main = "worker.js"            # Chỉ thẳng vào file trong cùng thư mục con
compatibility_date = "2026-07-03" # Sử dụng ngày hiện tại làm mốc tương thích

# Liên kết Database D1 SQLite của bạn (Thay thông số thực tế của bạn vào)
[[d1_databases]]
binding = "DB"
database_name = "Tên_database_D1_của_bạn"
database_id = "Mã_Database_ID_D1_của_bạn"
